sudo: required
services:
    - docker

before_install:
    - docker build -t 7immyh/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true 7immyh/react-test npm test

after_success: 
    - docker build -t 7immyh/multi-client ./client
    - docker build -t 7immyh/multi-nginx ./nginx
    - docker build -t 7immyh/multi-server ./server
    - docker build -t 7immyh/multi-worker ./worker
    #Log in to docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #Take images and push into Docker hub
    - docker push 7immyh/multi-client
    - docker push 7immyh/multi-nginx
    - docker push 7immyh/multi-server
    - docker push 7immyh/multi-worker
    
